# tipo_hospital.py

tipo_hospital = {
    'C0': {'MATUTINA': 0, 'VESPERTINA': 0, 'VELADA A': 0, 'VELADA B': 0,
           'ESPECIAL DIURNA': 0, 'ESPECIAL NOCTURNA': 0, 'JORNADA ACUMULADA': 0, 'NO_DEFINIDO': 0},
    'C30': {'MATUTINA': 72, 'VESPERTINA': 29, 'VELADA A': 9, 'VELADA B': 8,
            'ESPECIAL DIURNA': 10, 'ESPECIAL NOCTURNA': 0, 'JORNADA ACUMULADA': 0, 'NO_DEFINIDO': 0},
    'C60': {'MATUTINA': 123, 'VESPERTINA': 56, 'VELADA A': 31, 'VELADA B': 29,
            'ESPECIAL DIURNA': 30, 'ESPECIAL NOCTURNA': 0, 'JORNADA ACUMULADA': 0, 'NO_DEFINIDO': 0},
    'C90': {'MATUTINA': 229, 'VESPERTINA': 115, 'VELADA A': 60, 'VELADA B': 46,
            'ESPECIAL DIURNA': 36, 'ESPECIAL NOCTURNA': 1, 'JORNADA ACUMULADA': 0, 'NO_DEFINIDO': 0},
    'C120': {'MATUTINA': 269, 'VESPERTINA': 144, 'VELADA A': 71, 'VELADA B': 64,
             'ESPECIAL DIURNA': 44, 'ESPECIAL NOCTURNA': 9, 'JORNADA ACUMULADA': 0, 'NO_DEFINIDO': 0},
}
